language: php
php:
  - 7.0
  - 7.1

services:
    - memcached

before_script:
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu; fi;

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-text

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar
